// packages/solid/src/jsx.ts
/**
 * SolidJS JSX 类型增强：让 <wc-*> 标签获得属性类型检查。
 * 由 @wc-kit/core 的元素类实例类型自动推导（Partial<T>），与核心包保持同步、零手工维护。
 *
 * Solid 对自定义元素默认把 props 设为 property（attr: 前缀才是 attribute），
 * 对象数组、函数等复杂值原样传入——与 Lit 组件天然契合。
 *
 * 在应用入口 `import '@wc-kit/solid'`（副作用导入会同时注册全部自定义元素）即可激活增强。
 */
import type { JSX } from 'solid-js';
import type {
  wcBadge,
  wcBreadcrumb,
  wcBreadcrumbItem,
  wcButton,
  wcButtonGroup,
  wcAvatar,
  wcCard,
  wcCheckbox,
  wcCol,
  wcDatePicker,
  wcDateRangePicker,
  wcDialog,
  wcDivider,
  wcDrawer,
  wcDropdown,
  wcDropdownItem,
  wcSplitButton,
  wcFloatButton,
  wcFloatButtonGroup,
  wcEmpty,
  wcForm,
  wcFormItem,
  wcInput,
  wcInputNumber,
  wcList,
  wcListItem,
  wcMessage,
  wcMenu,
  wcMenuItem,
  wcSubMenu,
  wcAnchor,
  wcAnchorLink,
  wcAlert,
  wcSkeleton,
  wcSkeletonItem,
  wcCollapse,
  wcCollapseItem,
  wcSegmented,
  wcSegmentedItem,
  wcOption,
  wcPagination,
  wcPopconfirm,
  wcProgress,
  wcRadio,
  wcRow,
  wcLayout,
  wcLayoutHeader,
  wcLayoutContent,
  wcLayoutFooter,
  wcLayoutSider,
  wcSelect,
  wcSlider,
  wcSpace,
  wcSplitter,
  wcSplitterPanel,
  wcSwitch,
  wcTab,
  wcTable,
  wcTablePager,
  wcImage,
  wcTabs,
  wcTag,
  wcText,
  wcTextarea,
  wcTooltip,
  wcUpload,
  WcIcon,
} from '@wc-kit/core';

/**
 * 单个 <wc-*> 标签的类型：元素实例属性（Partial<T>）+ 标准 HTML 属性 +
 * Solid 自定义事件属性（on:wc-change 等，放宽为任意事件处理器）。
 */
type WcSolidTag<T extends HTMLElement> = Partial<T> &
  JSX.HTMLAttributes<T> & {
    [key: `on:${string}`]: unknown;
  };

declare module 'solid-js' {
  namespace JSX {
    interface IntrinsicElements {
      // 基础
      'wc-button': WcSolidTag<wcButton>;
      'wc-button-group': WcSolidTag<wcButtonGroup>;
      'wc-icon': WcSolidTag<WcIcon>;
      'wc-divider': WcSolidTag<wcDivider>;
      'wc-tag': WcSolidTag<wcTag>;
      'wc-avatar': WcSolidTag<wcAvatar>;
      'wc-space': WcSolidTag<wcSpace>;
      'wc-splitter': WcSolidTag<wcSplitter>;
      'wc-splitter-panel': WcSolidTag<wcSplitterPanel>;
      'wc-row': WcSolidTag<wcRow>;
      'wc-col': WcSolidTag<wcCol>;
      'wc-layout': WcSolidTag<wcLayout>;
      'wc-layout-header': WcSolidTag<wcLayoutHeader>;
      'wc-layout-content': WcSolidTag<wcLayoutContent>;
      'wc-layout-footer': WcSolidTag<wcLayoutFooter>;
      'wc-layout-sider': WcSolidTag<wcLayoutSider>;
      'wc-text': WcSolidTag<wcText>;
      // 表单
      'wc-input': WcSolidTag<wcInput>;
      'wc-textarea': WcSolidTag<wcTextarea>;
      'wc-select': WcSolidTag<wcSelect>;
      'wc-option': WcSolidTag<wcOption>;
      'wc-checkbox': WcSolidTag<wcCheckbox>;
      'wc-radio': WcSolidTag<wcRadio>;
      'wc-switch': WcSolidTag<wcSwitch>;
      'wc-slider': WcSolidTag<wcSlider>;
      'wc-input-number': WcSolidTag<wcInputNumber>;
      'wc-date-picker': WcSolidTag<wcDatePicker>;
      'wc-date-range-picker': WcSolidTag<wcDateRangePicker>;
      'wc-form': WcSolidTag<wcForm>;
      'wc-form-item': WcSolidTag<wcFormItem>;
      'wc-upload': WcSolidTag<wcUpload>;
      // 反馈
      'wc-dialog': WcSolidTag<wcDialog>;
      'wc-alert': WcSolidTag<wcAlert>;
      'wc-drawer': WcSolidTag<wcDrawer>;
      'wc-message': WcSolidTag<wcMessage>;
      'wc-tooltip': WcSolidTag<wcTooltip>;
      'wc-popconfirm': WcSolidTag<wcPopconfirm>;
      'wc-dropdown': WcSolidTag<wcDropdown>;
      'wc-dropdown-item': WcSolidTag<wcDropdownItem>;
      'wc-menu': WcSolidTag<wcMenu>;
      'wc-menu-item': WcSolidTag<wcMenuItem>;
      'wc-sub-menu': WcSolidTag<wcSubMenu>;
      'wc-split-button': WcSolidTag<wcSplitButton>;
      'wc-float-button': WcSolidTag<wcFloatButton>;
      'wc-float-button-group': WcSolidTag<wcFloatButtonGroup>;
      // 导航
      'wc-tabs': WcSolidTag<wcTabs>;
      'wc-tab': WcSolidTag<wcTab>;
      'wc-breadcrumb': WcSolidTag<wcBreadcrumb>;
      'wc-breadcrumb-item': WcSolidTag<wcBreadcrumbItem>;
      'wc-anchor': WcSolidTag<wcAnchor>;
      'wc-anchor-link': WcSolidTag<wcAnchorLink>;
      'wc-pagination': WcSolidTag<wcPagination>;
      // 数据展示
      'wc-badge': WcSolidTag<wcBadge>;
      'wc-empty': WcSolidTag<wcEmpty>;
      'wc-progress': WcSolidTag<wcProgress>;
      'wc-card': WcSolidTag<wcCard>;
      'wc-list': WcSolidTag<wcList>;
      'wc-list-item': WcSolidTag<wcListItem>;
      'wc-table': WcSolidTag<wcTable>;
      'wc-table-pager': WcSolidTag<wcTablePager>;
      'wc-image': WcSolidTag<wcImage>;
      'wc-skeleton': WcSolidTag<wcSkeleton>;
      'wc-skeleton-item': WcSolidTag<wcSkeletonItem>;
      'wc-collapse': WcSolidTag<wcCollapse>;
      'wc-collapse-item': WcSolidTag<wcCollapseItem>;
      'wc-segmented': WcSolidTag<wcSegmented>;
      'wc-segmented-item': WcSolidTag<wcSegmentedItem>;
    }
  }
}

export {};

// packages/react/src/jsx.ts
/**
 * 原生标签的 JSX 类型增强：React 用户在 TSX 里直接写 <wc-button> 等标签也有完整类型。
 * - ref 会推导为对应的 core 元素类（如 RefObject<WcButtonElement>）
 * - 属性层面放行任意 attribute（原生自定义元素的 attribute 本就是弱类型字符串；
 *   需要严格的属性/事件类型请用本包导出的包装组件，如 <WcButton onWcClick={...} />）
 * - 新增组件时同步在 WcTags 登记一条（与 core 各组件的 HTMLElementTagNameMap 保持一致）
 *
 * 兼容 React 18（全局 JSX namespace）与 React 19（React.JSX namespace）两种类型布局。
 */
import type * as React from 'react';
import type {
  wcAlert,
  wcAnchor,
  wcAnchorLink,
  wcAvatar,
  wcBadge,
  wcBreadcrumb,
  wcBreadcrumbItem,
  wcButton,
  wcButtonGroup,
  wcCard,
  wcCheckbox,
  wcCol,
  wcCollapse,
  wcCollapseItem,
  wcDatePicker,
  wcDateRangePicker,
  wcDialog,
  wcDivider,
  wcDrawer,
  wcDropdown,
  wcDropdownItem,
  wcEmpty,
  wcFloatButton,
  wcFloatButtonGroup,
  wcForm,
  wcFormItem,
  WcIcon,
  wcImage,
  wcInput,
  wcInputNumber,
  wcLayout,
  wcLayoutContent,
  wcLayoutFooter,
  wcLayoutHeader,
  wcLayoutSider,
  wcList,
  wcListItem,
  wcMenu,
  wcMenuItem,
  wcMessage,
  wcOption,
  wcPagination,
  wcPopconfirm,
  wcProgress,
  wcRadio,
  wcRow,
  wcSelect,
  wcSegmented,
  wcSegmentedItem,
  wcSkeleton,
  wcSkeletonItem,
  wcSlider,
  wcSpace,
  wcSplitButton,
  wcSplitter,
  wcSplitterPanel,
  wcSubMenu,
  wcSwitch,
  wcTab,
  wcTable,
  wcTablePager,
  wcTabs,
  wcTag,
  wcText,
  wcTextarea,
  wcTooltip,
  wcUpload,
} from '@wc-kit/core';

type WcIntrinsic<T extends HTMLElement> = React.DetailedHTMLProps<React.HTMLAttributes<T>, T> &
  Record<string, unknown>;

interface WcTags {
  'wc-alert': WcIntrinsic<wcAlert>;
  'wc-anchor': WcIntrinsic<wcAnchor>;
  'wc-anchor-link': WcIntrinsic<wcAnchorLink>;
  'wc-avatar': WcIntrinsic<wcAvatar>;
  'wc-badge': WcIntrinsic<wcBadge>;
  'wc-breadcrumb': WcIntrinsic<wcBreadcrumb>;
  'wc-breadcrumb-item': WcIntrinsic<wcBreadcrumbItem>;
  'wc-button': WcIntrinsic<wcButton>;
  'wc-button-group': WcIntrinsic<wcButtonGroup>;
  'wc-card': WcIntrinsic<wcCard>;
  'wc-checkbox': WcIntrinsic<wcCheckbox>;
  'wc-col': WcIntrinsic<wcCol>;
  'wc-collapse': WcIntrinsic<wcCollapse>;
  'wc-collapse-item': WcIntrinsic<wcCollapseItem>;
  'wc-date-picker': WcIntrinsic<wcDatePicker>;
  'wc-date-range-picker': WcIntrinsic<wcDateRangePicker>;
  'wc-dialog': WcIntrinsic<wcDialog>;
  'wc-divider': WcIntrinsic<wcDivider>;
  'wc-drawer': WcIntrinsic<wcDrawer>;
  'wc-dropdown': WcIntrinsic<wcDropdown>;
  'wc-dropdown-item': WcIntrinsic<wcDropdownItem>;
  'wc-empty': WcIntrinsic<wcEmpty>;
  'wc-float-button': WcIntrinsic<wcFloatButton>;
  'wc-float-button-group': WcIntrinsic<wcFloatButtonGroup>;
  'wc-form': WcIntrinsic<wcForm>;
  'wc-form-item': WcIntrinsic<wcFormItem>;
  'wc-icon': WcIntrinsic<WcIcon>;
  'wc-image': WcIntrinsic<wcImage>;
  'wc-input': WcIntrinsic<wcInput>;
  'wc-input-number': WcIntrinsic<wcInputNumber>;
  'wc-layout': WcIntrinsic<wcLayout>;
  'wc-layout-content': WcIntrinsic<wcLayoutContent>;
  'wc-layout-footer': WcIntrinsic<wcLayoutFooter>;
  'wc-layout-header': WcIntrinsic<wcLayoutHeader>;
  'wc-layout-sider': WcIntrinsic<wcLayoutSider>;
  'wc-list': WcIntrinsic<wcList>;
  'wc-list-item': WcIntrinsic<wcListItem>;
  'wc-menu': WcIntrinsic<wcMenu>;
  'wc-menu-item': WcIntrinsic<wcMenuItem>;
  'wc-message': WcIntrinsic<wcMessage>;
  'wc-option': WcIntrinsic<wcOption>;
  'wc-pagination': WcIntrinsic<wcPagination>;
  'wc-popconfirm': WcIntrinsic<wcPopconfirm>;
  'wc-progress': WcIntrinsic<wcProgress>;
  'wc-radio': WcIntrinsic<wcRadio>;
  'wc-row': WcIntrinsic<wcRow>;
  'wc-select': WcIntrinsic<wcSelect>;
  'wc-segmented': WcIntrinsic<wcSegmented>;
  'wc-segmented-item': WcIntrinsic<wcSegmentedItem>;
  'wc-skeleton': WcIntrinsic<wcSkeleton>;
  'wc-skeleton-item': WcIntrinsic<wcSkeletonItem>;
  'wc-slider': WcIntrinsic<wcSlider>;
  'wc-space': WcIntrinsic<wcSpace>;
  'wc-split-button': WcIntrinsic<wcSplitButton>;
  'wc-splitter': WcIntrinsic<wcSplitter>;
  'wc-splitter-panel': WcIntrinsic<wcSplitterPanel>;
  'wc-sub-menu': WcIntrinsic<wcSubMenu>;
  'wc-switch': WcIntrinsic<wcSwitch>;
  'wc-tab': WcIntrinsic<wcTab>;
  'wc-table': WcIntrinsic<wcTable>;
  'wc-table-pager': WcIntrinsic<wcTablePager>;
  'wc-tabs': WcIntrinsic<wcTabs>;
  'wc-tag': WcIntrinsic<wcTag>;
  'wc-text': WcIntrinsic<wcText>;
  'wc-textarea': WcIntrinsic<wcTextarea>;
  'wc-tooltip': WcIntrinsic<wcTooltip>;
  'wc-upload': WcIntrinsic<wcUpload>;
}

declare global {
  namespace JSX {
    // React 18 类型布局：全局 JSX namespace
    interface IntrinsicElements extends WcTags {}
  }
}

declare module 'react' {
  namespace JSX {
    // React 19 类型布局：JSX namespace 移入 react 模块
    interface IntrinsicElements extends WcTags {}
  }
}

// 导出类型使本模块被 index 引用，从而让 JSX 增强随包发布并生效
export type { WcTags };
